var total_item = [
  {

    //MAN OVERSIZED FIT SECTION STARTS--
    img:"https://images.bewakoof.com/t640/men-s-purple-beast-within-2-0-oversized-t-shirt-581488-1677228989-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Purple Beast Within Graphic Printed Oversized0 T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design: ["OVERSIZED0 FIT"],
    color :["purple"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-blue-bones-graphic-printed-oversized-t-shirt-589386-1681726048-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Blue Bones Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT"] ,
    color :["blue"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-green-the-man-of-steel-graphic-printed-oversized-t-shirt-589395-1681725064-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Green The Man Of Steel Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["green"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-purple-cyber-samurai-graphic-printed-oversized-t-shirt-589387-1681725657-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Purple Cyber Samurai Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["purple"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-white-the-man-of-steel-graphic-printed-oversized-t-shirt-589394-1681725417-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's White The Man Of Steel Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["white"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-blue-beetle-graphic-printed-oversized-t-shirt-589381-1681725577-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Purple Blue Beetle Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["blue","purple"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-best-buds-graphic-printed-oversized-t-shirt-589392-1681725968-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Purple Best Buds Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["purple"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-fly-me-to-the-moon-graphic-printed-oversized-t-shirt-505572-1667492228-1.jpg",
    merchandise:"OFFICIAL NASA MERCHANDISE",
    name: "Men's Black Fly Me To The Moon Graphic Printed Oversized T-shirt",
    rating: 4.3,
    price: 799,
    mrp: 1299,
    off:"53%",
    fit_design:["OVERSIZED FIT"] ,
    color:["black"],
    size: ['m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-white-karma-circles-typography-oversized-t-shirt-489752-1681218931-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's White Karma Circles Typography Oversized T-shirt",
    rating: 4.1,
    price: 754,
    mrp: 1049,
    off:"47%",
    fit_design:["OVERSIZED FIT"] ,
    color:["white"],
    size: ['s','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-blue-peace-not-war-graphic-printed-oversized-t-shirt-479634-1667556897-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Peace Not War Graphic Printed Oversized T-shirt",
    rating: 4.1,
    price: 566,
    mrp: 1049,
    off:"47%",
    fit_design:["OVERSIZED FIT"] ,
    color:["blue"],
    size: ['s','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-warriors-graphic-printed-oversized-t-shirt-519149-1679048409-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Warriors Graphic Printed Oversized T-shirt",
    rating: 4.4,
    price: 599,
    mrp: 1049,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["black"],
    size: ['s','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-blue-oversized-fit-t-shirt-439435-1681218476-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Oversized Fit T-shirt",
    rating: 4.4,
    price: 499,
    mrp: 799,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["blue"],
    size: ['s','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-blue-oversized-fit-t-shirt-439435-1681218476-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Oversized Fit T-shirt",
    rating: 4.4,
    price: 499,
    mrp: 799,
    off:"53%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["blue","green"],
    size: ['s','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-bright-white-color-block-oversized-t-shirt-509375-1667977333-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's White & Blue Color Block Oversized T-shirt",
    rating: 4.4,
    price: 479,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["white","black"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-empire-yellow-oversized-t-shirt-492722-1667556087-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Empire Yellow Oversized T-shirt",
    rating: 4.4,
    price: 392,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["yellow"],
    size: ['m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-mickey-move-printed-t-shirt-558411-1674813700-1.jpg",
    merchandise:"OFFICIAL DISNEY MERCHANDISE",
    name: "Men's White Mickey Move Graphic Printed Oversized T-shirt",
    rating: 4.4,
    price: 809,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["white"],
    size: ['m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-mickey-crew-stripe-printed-t-shirt-563345-1672135307-1.jpg",
    merchandise:"OFFICIAL DISNEY MERCHANDISE",
    name: "Men's Green Mickey Crew Graphic Printed Oversized T-shirt",
    rating: 4.4,
    price: 409,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["green","black"],
    size: ['m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-batman-knight-graphic-printed-oversized-t-shirt-479704-1676372000-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Black Batman Knight Graphic Printed Oversized T-shirt",
    rating: 4.4,
    price: 409,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["green","black"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-white-disney-original-crew-printed-t-shirt-516641-1667911995-1.jpg",
    merchandise:"BEWAKOOF X STREETWEAR",
    name: "Men's White Disney Crew Graphic Printed Oversized T-shirt",
    rating: 4.4,
    price: 539,
    mrp: 1399,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["white"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-varsity-green-college-dropout-typography-oversized-t-shirt-512520-1667497051-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Varsity Green College Dropout Typography Oversized T-shirt",
    rating: 4.4,
    price: 584,
    mrp: 1199,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["green"],
    size: ['s','m','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-snorkel-blue-color-block-oversized-hoodie-t-shirt-509388-1669723124-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue & Pink Color Block Oversized Hoodie T-shirt",
    rating: 4.7,
    price: 584,
    mrp: 1199,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["blue"],
    size: ['s','m','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-gray-flannel-eva01-printed-t-shirt-542572-1672842845-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Grey EVA01 Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 518,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["grey","purple"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-the-ghost-graphic-printed-oversized-t-shirt-503830-1681218572-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black The Ghost Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 614,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["black"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-red-striped-oversized-t-shirt-544716-1670995812-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black & Red Striped Oversized T-shirt",
    rating: 4.6,
    price: 668,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["red"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-oversized-t-shirt-439421-1679048737-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Oversized T-shirt",
    rating: 4.6,
    price: 648,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black","red","blue"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-red-striped-oversized-t-shirt-425013-1667553371-1.jpg",
    merchandise:"BEWAKOOF X STREETWEAR",
    name: "Men's Black Oversized T-shirt",
    rating: 4.2,
    price: 699,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["red"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-green-white-striped-oversized-t-shirt-516667-1673444594-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Green & White Striped Oversized T-shirt",
    rating: 4.2,
    price: 539,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["green"],
    size: ['m','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-universal-astro-graphic-printed-oversized-t-shirt-516917-1679048996-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Universal Astro Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 799,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-scribble-aop-oversized-t-shirt-516662-1674553389-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Scribble AOP Oversized T-shirt",
    rating: 4.2,
    price: 547,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-grey-graphic-printed-oversized-t-shirt-507999-1672743406-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Scribble AOP Oversized T-shirt",
    rating: 4.2,
    price: 539,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["grey"],
    size: ['m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-white-marvel-ironman-typography-oversized-t-shirt-519161-1670996699-1.jpg",
    merchandise:"OFFICIAL MARVEL MERCHANDISE",
    name: "Men's Black Scribble AOP Oversized T-shirt",
    rating: 4.2,
    price: 399,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["white"],
    size: ['m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-dark-shadow-rise-of-guru-graphic-printed-oversized-t-shirt-546423-1670247091-1.jpg",
    merchandise:"OFFICIAL MINIONS MERCHANDISE",
    name: "Men's Dark Shadow Rise of Guru Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 399,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:[null],
    size: ['m','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-witcher-of-rivia-graphic-printed-oversized-t-shirt-519192-1667519467-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Witcher of Rivia Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 649,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/chilled-out-green-stripe-t-shirt-516728-1668168293-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Chilled Out Green Striped Oversized T-shirt",
    rating: 4.2,
    price: 523,
    mrp: 1399,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["green"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-gulf-coast-black-printed-t-shirt-547976-1679924214-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Chilled Out Green Striped Oversized T-shirt",
    rating: 4.2,
    price: 799,
    mrp: 1699,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-respawn-gamer-graphic-printed-oversized-t-shirt-502032-1667499379-1.jpg?tr=q-100",
    merchandise:"Bewakoof®",
    name: "Men's Chilled Out Green Striped Oversized T-shirt",
    rating: 4.2,
    price: 649,
    mrp: 1199,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-grey-shape-shifter-typography-oversized-t-shirt-558401-1672830294-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Grey Shape Shifter Typography Oversized T-shirt",
    rating: 4.2,
    price: 599,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["grey"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-venom-street-graphic-printed-oversized-t-shirt-547537-1670828932-1.jpg",
    merchandise:"OFFICIAL MARVEL MERCHANDISE",
    name: "Men's Purple Venom Street Graphic Printed Oversized T-shirt",
    rating: 4.2,
    price: 749,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["purple"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-white-vengeance-typography-oversized-t-shirt-519142-1680514083-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's White Vengeance Typography Oversized T-shirt",
    rating: 4.2,
    price: 549,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["white"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-white-printed-t-shirt-548177-1679924534-1.jpg",
    merchandise:"OFFICIAL DISNEY MERCHANDISE",
    name: "Men's White Cra Striped Oversized T-shirt",
    rating: 4.2,
    price: 749,
    mrp: 1699,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["white"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-black-white-printed-t-shirt-547960-1679924701-1.jpg",
    merchandise:"OFFICIAL PEANUTS MERCHANDISE",
    name: "Men's Black Pea Color Block Oversized T-shirt",
    rating: 4.2,
    price: 999,
    mrp: 1999,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black","grey"],
    size: ['m'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-red-the-batman-oversized-fit-t-shirt-480316-1667507467-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Red The Batman Graphic Printed Oversized T-shirt",
    rating: 4.1,
    price: 599,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black","red","white"],
    size: ['m'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-lavender-my-hero-academia-graphic-printed-oversized-t-shirt-583270-1678775806-1.jpg",
    merchandise:"The bargain street",
    name: "Men's Lavender My hero academia Graphic Printed Oversized T-shirt",
    rating: 4.1,
    price: 699,
    mrp: 1299,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black","red","white"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/teeshut-men-s-green-hunter-graphic-printed-oversized-t-shirt-578983-1675755778-1.jpg",
    merchandise:"TEESHUT",
    name: "Men's Green Hunter Graphic Printed Oversized T Shirt",
    rating: 4.1,
    price: 580,
    mrp: 999,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["green"],
    size: ['s','m','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-aop-oversized-t-shirt-425019-1667560056-1.jpg",
    merchandise:"BEWAKOOF X STREETWEAR",
    name: "Men's Black AOP Oversized T-shirt",
    rating: 4.1,
    price: 849,
    mrp: 999,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["black"],
    size: ['s','m','l'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-red-nasa-astronaut-graphic-printed-oversized-t-shirt-502021-1667496770-1.jpg",
    merchandise:"OFFICIAL NASA MERCHANDISE",
    name: "Men's Red NASA Astronaut Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 599,
    mrp: 1499,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["red"],
    size: ['s','m','l','xl','2xl','3xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-the-boys-typographic-oversized-t-shirt-581770-1677237221-1.jpg",
    merchandise:"Mad Over Print",
    name: "Men's Black The Boys Typographic Oversized T-shirt",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["black"],
    size: ['s','m','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-white-thug-life-graphic-printed-oversized-t-shirt-546319-1664777088-1.jpg",
    merchandise:"TEESHUT",
    name: "Men's White Thug Life Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["white"],
    size: ['s','m','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-gotham-world-printed-t-shirt-19-582409-1680612073-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's Purple Gotham World Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["purple"],
    size: ['s','m','l','xl','2xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //MAN OVERSIZED FIT SECTION ENDS--
  //----------
  //NEW ARRIVAL FOR BOTH
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-shelby-brother-graphic-printed-plus-size-t-shirt-589268-1681392029-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Shelby Brother Graphic Printed Plus Size T-shirt",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["DIGITAL PRINT","100% COTTON"] ,
    color:["black"],
    size: ['2xl','3xl','4xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-i-need-some-space-teddy-graphic-printed-plus-size-t-shirt-589270-1681391949-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Area 51 Keep Out Graphic Printed Plus Size T-shirt",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["DIGITAL PRINT","100% COTTON"] ,
    color:["black"],
    size: ['2xl','3xl','4xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-be-rad-graphic-printed-boyfriend-t-shirt-589602-1681816746-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Blue Be Rad Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 399,
    mrp: 1599,
    off:"63%",
    fit_design:["BOYFRIEND FIT","DIGITAL PRINT","100% COTTON"] ,
    color:["blue"],
    size: ['s','m','l','2xl','3xl','4xl'],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-sunset-block-graphic-printed-plus-size-t-shirt-589267-1681391917-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Sunset Block Graphic Printed Plus Size T-shirt",
    rating: 4.6,
    price: 399,
    mrp: 1599,
    off:"63%",
    fit_design:["DIGITAL PRINT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','l','2xl','3xl','4xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-white-the-man-of-steel-graphic-printed-t-shirt-589396-1681725620-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's White The Man Of Steel Graphic Printed T-shirt",
    rating: 4.6,
    price: 499,
    mrp: 1599,
    off:"63%",
    fit_design:["DIGITAL PRINT","100% COTTON"] ,
    color:["white"],
    size: ['s','m','l','2xl','3xl','4xl'],
    gender: "male",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-purple-be-rad-graphic-printed-oversized-t-shirt-589393-1681883933-1.jpg ",
    merchandise:"Bewakoof®",
    name: "Women's Purple Be Rad Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"],
    color:["purple"],
    size: ['xs','s','m','l','2xl','3xl','4xl'],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-green-best-buds-graphic-printed-slim-fit-tank-top-589549-1681725893-1.jpg",
    merchandise:"OFFICIAL MINIONS MERCHANDISE",
    name: "Women's Green Best Buds Graphic Printed Slim Fit Tank Top",
    rating: 4.6,
    price: 299,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","DESIGN OF THE WEEK","100% COTTON"],
    color:["green"],
    size: ['xs','s','m','l','2xl','3xl','4xl'],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-red-cute-but-psycho-graphic-printed-plus-size-boyfriend-t-shirt-589376-1681725342-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Red Cute But Psycho Graphic Printed Plus Size Boyfriend T-shirt",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE","DESIGN OF THE WEEK","100% COTTON"],
    color:["red"],
    size: ['2xl','3xl','4xl','5xl','6xl'],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-pink-cute-but-psycho-graphic-printed-boyfriend-t-shirt-589385-1681884713-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Pink Cute But Psycho Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 349,
    mrp: 1599,
    off:"63%",
    fit_design:["BOYFRIEND FIT","DIGITAL PRINT","100% COTTON"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-red-cute-but-psycho-graphic-printed-oversized-t-shirt-589390-1681885794-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's red Cute But Psycho Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 349,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-pink-best-buds-graphic-printed-oversized-t-shirt-589379-1681725219-1.jpg",
    merchandise:"OFFICIAL MINIONS MERCHANDISE",
    name: "Women's pink Cute But Psycho Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 349,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-orange-cute-but-psycho-graphic-printed-boyfriend-t-shirt-589391-1681886094-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's orange Cute But Psycho Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 349,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["orange"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-party-planning-committee-graphic-printed-boyfriend-t-shirt-30-585766-1681281298-1.jpg",
    merchandise:"OFFICIAL THE OFFICE MERCHANDISE",
    name: "Women's Green Party Planning Committee Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 349,
    mrp: 1599,
    off:"63%",
    fit_design:["BOYFRIEND FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-party-planning-committee-graphic-printed-oversized-t-shirt-33-585749-1681281639-1.jpg",
    merchandise:"OFFICIAL THE OFFICE MERCHANDISE",
    name: "Women's pink Party Planning Committee Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 599,
    mrp: 1599,
    off:"63%",
    fit_design:["DESIGN OF THE WEEK","100% COTTON"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-whatever-cat-graphic-printed-plus-size-boyfriend-t-shirt-579014-1681218598-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's blue Party Planning Committee Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 599,
    mrp: 1599,
    off:"63%",
    fit_design:["DESIGN OF THE WEEK","100% COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-nebula-blue-solid-jogger-507380-1680593246-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Blue Joggers",
    rating: 4.6,
    price: 899,
    mrp: 1599,
    off:"63%",
    fit_design:["PREMIUM TERRY COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/despicable-jg-joggers-452397-1677739363-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's black Joggers",
    rating: 4.6,
    price: 906,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","SOFT TERRY COTTON"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-garfield-s-personalities-printed-dress-36-582424-1678112524-1.jpg",
    merchandise:"OFFICIAL GARFIELD MERCHANDISE",
    name: "Women's Black Garfield's Personalities Graphic Printed Oversized Dress",
    rating: 4.6,
    price: 999,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","100% COTTON"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "DRESS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-brown-ribbed-johnny-collar-slim-fit-dress-556814-1680689165-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Brown Ribbed Johnny Collar Slim Fit Dress",
    rating: 4.6,
    price: 799,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "DRESS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-butterfly-theory-graphic-printed-oversized-dress-584834-1679394933-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Black Butterfly Theory Graphic Printed Oversized Dress",
    rating: 4.6,
    price: 899,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "DRESS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-snoopy-illusion-printed-dress-3-582454-1679302106-1.jpg",
    merchandise:"OFFICIAL PEANUTS MERCHANDISE",
    name: "WWomen's Teal Green Snoopy Illusion Graphic Printed Oversized Dress",
    rating: 4.6,
    price: 799,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","SOFT TERRY COTTON"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "DRESS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-3-589501-1681479413-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-3-589501-1681479413-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-2-589479-1681479788-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-3-589501-1681479413-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-3-589501-1681479413-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-all-over-printed-boxer-combo-pack-of-2-589489-1681479627-1.jpg",
    merchandise:"Bewakoof®",
    name: "Pack of 3 Men's Blue All Over Printed Boxers",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "BOXERS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/game-of-thrones-poplin-pyjama-gtl-265250-1656092215-1.jpg",
    merchandise:"OFFICIAL GAME OF THRONES MERCHANDISE",
    name: "Men's Black Game Of Thrones Printed Pyjamas",
    rating: 4.6,
    price: 699,
    mrp: 1599,
    off:"63%",
    fit_design:["100% COTTON"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "PYJAMAS",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  //NEW ARRIVAL ENDS---
  //-------------
  //BEST SELLERS FOR WOMEN STARTS---
  {
    img:"https://www.bewakoof.com/p/jet-black-half-sleeve-plain-t-shirt-for-women",
    merchandise:"Bewakoof®",
    name: "Women's Black Slim Fit T-shirt",
    rating: 4.6,
    price: 269,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-white-peeking-army-graphic-printed-boyfriend-t-shirt-519415-1680593017-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's White Peeking Army Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["BOYFRIEND FIT"] ,
    color:["white"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-red-pocket-jerry-slim-fit-t-shirt-242006-1655747764-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Red Pocket Jerry Slim Fit T-shirt",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/women-s-white-motd-panda-t-shirt-479771-1655815714-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Red Pocket Jerry Slim Fit T-shirt",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["white"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-red-boyfriend-t-shirt-170465-1658918677-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Red Pocket Jerry Slim Fit T-shirt",
    rating: 4.6,
    price: 326,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/inner-peace-half-sleeve-printed-t-shirt-black-295708-1655749271-1.jpg",
    merchandise:"Bewakoof®",
    name: "Inner Peace Half Sleeve Printed T-Shirt Black",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/hello-sunshine-boyfriend-t-shirt-navy-blue-296647-1655748887-1.jpg",
    merchandise:"Bewakoof®",
    name: "Hello Sunshine Boyfriend T-Shirt Navy Blue",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-friends-typography-boyfriend-t-shirt-234669-1655810540-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Purple Be Rad Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT","DESIGN OF THE WEEK","100% COTTON"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/friends-logo-boyfriend-t-shirt-frl-238060-1655748560-1.jpg",
    merchandise:"Bewakoof®",
    name: "Hello Sunshine Boyfriend T-Shirt Navy Blue",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-friends-typography-boyfriend-t-shirt-234669-1655810540-1.jpg",
    merchandise:"Bewakoof®",
    name: "Hello Sunshine Boyfriend T-Shirt Navy Blue",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  //BEST SELLERS FOR WOMEN ENDS---
  //-----------
  //Printed T Shirts for Women and T-shhirt for women are same.
  //according to merchandise--
  {
    img:"https://images.bewakoof.com/t640/women-s-black-graphic-printed-t-shirt-581856-1677591932-1.jpg",
    merchandise:"Botnia",
    name: "Women's Black Ramen Cat Graphic Printed T-shirt",
    rating: 4.6,
    price: 629,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT","BOYFRIEND FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-typographic-t-shirt-581866-1677591716-1.jpg",
    merchandise:"Botnia",
    name: "Women's Black Coca-Cola Typographic T-shirt",
    rating: 4.6,
    price: 629,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-purple-joey-doesn-t-share-food-graphic-printed-t-shirt-581853-1677589615-1.png",
    merchandise:"Botnia",
    name: "Women's Purple Joey Doesn't Share Food Graphic Printed T-shirt",
    rating: 4.6,
    price: 629,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT","BOYFRIEND FIT"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-white-depressed-but-cool-graphic-printed-oversized-t-shirt-1-570774-1673961454-1.jpg",
    merchandise:"Weezy",
    name: "Women's Purple Joey Doesn't Share Food Graphic Printed T-shirt",
    rating: 4.6,
    price: 685,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["white"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-archangel-graphic-printed-oversized-t-shirt-1-570777-1673961109-1.jpg",
    merchandise:"Weezy",
    name: "Women's Black Archangel Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 585,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-white-dragons-are-real-graphic-printed-oversized-t-shirt-1-570776-1673961364-1.jpg",
    merchandise:"Weezy",
    name: "Women's Black Archangel Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 585,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["white"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-you-typography-oversized-t-shirt-539647-1662107781-1.JPG",
    merchandise:"Door 74",
    name: "Women's Black You Typography Oversized T-shirt",
    rating: 4.6,
    price: 585,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-white-typography-oversized-t-shirt-539649-1662107670-1.JPG",
    merchandise:"Door 74",
    name: "Women's white You Typography Oversized T-shirt",
    rating: 4.6,
    price: 585,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["white"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: " T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t540/campus-sutra-women-solid-stylish-casual-bomber-jacket-446231-1636624940-1.jpg",
    merchandise:"Campus Sutra",
    name: "Women's Brown Stylish Casual Bomber Jacket",
    rating: 4.6,
    price: 1080,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["brown"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "jacket",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-pink-puffer-jacket-558010-1669984206-1.jpg",
    merchandise:"Campus Sutra",
    name: "Women's pink Stylish Casual Bomber Jacket",
    rating: 4.6,
    price: 1080,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "jacket",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-grey-tie-dye-shorts-39-587678-1681214383-1.jpg",
    merchandise:"Vastrado",
    name: "Women's Grey Tie & Dye Shorts",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["grey"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Shorts",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-olive-green-shorts-11-587663-1681213660-1.jpg",
    merchandise:"Vastrado",
    name: "Women's Olive Green Shorts",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Shorts",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-olive-green-shorts-11-587663-1681213660-1.jpg",
    merchandise:"Aks",
    name: "Blue & White Button Down Long Kurta",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Long Kurta",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-olive-green-shorts-11-587663-1681213660-1.jpg",
    merchandise:"Aks",
    name: "Blue & White Button Down Long Kurta",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Long Kurta",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-green-graphic-printed-relaxed-fit-t-shirt-535815-1660205882-1.jpg",
    merchandise:"Dillinger",
    name: "Women's Green Graphic Printed Relaxed Fit T-shirt",
    rating: 4.6,
    price: 549,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Long Kurta",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/clovia-women-s-pink-activewear-cargo-track-pants-577087-1674813630-1.jpg",
    merchandise:"Clovia",
    name: "Women's Pink Activewear Cargo Track Pants",
    rating: 4.6,
    price: 849,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Track Pants",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-printed-relaxed-fit-top-capri-set-589247-1681327065-1.jpg",
    merchandise:"Lounge Dreams",
    name: "Women's Blue Printed Relaxed Fit Top & Capri Set",
    rating: 4.6,
    price: 849,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Track Pants",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-straight-fit-trousers-584785-1679378306-1.JPG",
    merchandise:"Kotty",
    name: "Women's Black Straight Fit Trousers",
    rating: 4.6,
    price: 849,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Trousers",
    bestseller: true,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-love-peace-happiness-graphic-printed-t-shirt-509689-1656058758-1.jpg",
    merchandise:"Mad Over Print",
    name: "Women's Black Love Peace Happiness Graphic Printed T-shirt",
    rating: 4.6,
    price: 849,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-relaxed-fit-jeans-534240-1659599484-1.JPG",
    merchandise:"Zheia",
    name: "Women's Blue Relaxed Fit Jeans",
    rating: 4.6,
    price: 1059,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-minnie-full-sleeve-athleisure-t-shirt-463761-1658661919-1.jpg",
    merchandise:"OFFICIAL DISNEY MERCHANDISE",
    name: "Women's Blue Relaxed Fit Jeans",
    rating: 4.6,
    price: 149,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/freakins-women-maroon-solid-jogger-fit-joggers-450620-1655917537-1.jpg",
    merchandise:"Freakins",
    name: "Women Maroon Solid Jogger Fit Joggers",
    rating: 4.6,
    price: 1049,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["maroon"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-green-graphic-printed-loose-fit-t-shirt-536818-1660732473-1.jpg",
    merchandise:"THE DRY STATE",
    name: "Women Maroon Solid Jogger Fit T-shirt",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/dillinger-women-s-red-oversized-fit-t-shirt-456481-1656054760-1.jpg",
    merchandise:"Dillinger",
    name: "Women Maroon Solid Jogger Fit T-shirt",
    rating: 4.6,
    price: 249,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/dillinger-women-s-red-oversized-fit-t-shirt-456481-1656054760-1.jpg",
    merchandise:"Difference of Opinion",
    name: "Women Maroon Solid Jogger Fit T-shirt",
    rating: 4.6,
    price: 949,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-green-typographic-t-shirt-588962-1681379860-1.jpg",
    merchandise:"Belliskey",
    name: "Women Maroon Solid Jogger Fit T-shirt",
    rating: 4.6,
    price: 1049,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  //--------
  {
    img:"https://images.bewakoof.com/t1080/men-didn-t-do-it-minions-printed-t-shirt-581120-1679569999-1.jpg",
    merchandise:"OFFICIAL MINIONS MERCHANDISE",
    name: "Men's Lavender I Didn't Do It Minions Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-red-best-buds-graphic-printed-boyfriend-t-shirt-589378-1681725855-1.jpg",
    merchandise:"OFFICIAL MINIONS MERCHANDISE",
    name: "Women's Red Best Buds Graphic Printed Boyfriend T-shirt",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["red"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
//JOGGERS FOR MEN & WOMEN--
{
    img:"https://images.bewakoof.com/t640/jet-black-casual-jogger-pants-with-zipper-321141-1655751015-5.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Zipper Casual Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
{
    img:"https://images.bewakoof.com/t1080/sage-green-cotton-jogger-pants-330852-1663661717-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Zipper Casual Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
{
    img:"https://images.bewakoof.com/t640/jet-black-casual-jogger-pants-with-zipper-321141-1655751015-5.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Zipper Casual Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
{
    img:"https://images.bewakoof.com/t1080/men-s-black-logo-b-boy-printed-oversize-fit-joggers-554330-1670480234-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Logo B-Boy Typography Oversized Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["REGULAR FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: true,
  },
{
    img:"https://images.bewakoof.com/t1080/men-s-black-logo-b-boy-printed-oversize-fit-joggers-554330-1670480234-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Black Slim Fit Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
{
    img:"https://images.bewakoof.com/t1080/women-s-black-training-tights-456363-1658827635-1.jpg",
    merchandise:"PLAY BY BEWAKOOF",
    name: "Women's Black Slim Fit Joggers",
    rating: 4.6,
    price: 749,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Joggers",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  //mens shorts---
  {
    img:"https://images.bewakoof.com/t1080/navy-blue-plus-size-casual-shorts-324728-1655748266-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-green-down-town-typography-oversized-shorts-516600-1677654822-1.jpg",
    merchandise:"BEWAKOOF X STREETWEAR",
    name: "Men's Green Down Town Typography Oversized Shorts",
    rating: 4.6,
    price: 649,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/india-ink-casual-shorts-330310-1656162160-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's India Ink Casual Shorts",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-solid-sky-blue-shorts-564939-1680251970-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/moss-green-casual-shorts-293080-1656107949-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy grey Plus Size Casual Shorts",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/dark-maroon-casual-shorts-293081-1661433967-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 449,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["maroon"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-colorblock-shorts-459476-1661433612-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Black Colorblock Shorts",
    rating: 4.6,
    price: 438,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Shorts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //mens joggers---
  {
    img:"https://images.bewakoof.com/t1080/men-s-velvet-cake-solid-jogger-507383-1670936345-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Maroon Joggers",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["velvet"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-deep-depth-logo-b-boy-printed-oversize-fit-joggers-554329-1670480196-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Deep Depth Logo B-Boy Typography Oversized Joggers",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/charcoal-grey-jogger-pants-with-zipper-321137-1656184057-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Deep Depth Logo B-Boy Typography Oversized Joggers",
    rating: 4.6,
    price: 708,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["grey"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-joggers-451591-1656156783-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Purple Joggers",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-joggers-451591-1656156783-1.jpg",
    merchandise:"Hubberholme",
    name: "Men's Purple Joggers",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-joggers-451591-1656156783-1.jpg",
    merchandise:"Hubberholme",
    name: "Men's Purple Joggers",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-purple-joggers-451591-1656156783-1.jpg",
    merchandise:"Hubberholme",
    name: "Men's Purple Joggers",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-grey-track-pants-556687-1669359054-1.JPG",
    merchandise:"Chkokko",
    name: "Men's Grey Track Pants",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["grey"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-grey-track-pants-556687-1669359054-1.JPG",
    merchandise:"Breakbounce",
    name: "Men's Grey Track Pants",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["grey"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-stylish-striped-evening-trackpant-385626-1656169875-1.jpg",
    merchandise:"Campus Sutra",
    name: "Men's Grey Track Pants",
    rating: 4.6,
    price: 738,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["grey"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "joggers",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  //vest for men--
  {
    img:"https://images.bewakoof.com/t1080/jet-black-vest-210687-1659522825-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Jet Black Vest",
    rating: 4.6,
    price: 338,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Vest",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-aop-deep-armhole-vest-507963-1670935857-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue AOP Oversized Deep Armhole Vest",
    rating: 4.6,
    price: 399,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Vest",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-navy-blue-vest-210690-1673255698-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Jet Black Vest",
    rating: 4.6,
    price: 338,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["navy"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Vest",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  //full slevees tshits men--
  {
    img:"https://images.bewakoof.com/t1080/men-s-blue-bones-graphic-printed-oversized-t-shirt-589386-1681726048-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Bones Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Full Sleeve T-Shirts",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-green-the-man-of-steel-graphic-printed-oversized-t-shirt-589395-1681725064-1.jpg",
    merchandise:"OFFICIAL DC COMICS MERCHANDISE",
    name: "Men's greeb Bones Graphic Printed Oversized T-shirt",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["green"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Full Sleeve T-Shirts",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //Fashion Tops for women
  {
    img:"https://images.bewakoof.com/t1080/women-s-pink-slim-fit-ribbed-crop-top-551804-1680688929-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Pink Slim Fit Ribbed Crop Top",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Top",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-purple-slim-fit-ribbed-crop-top-551806-1680689499-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Pink Slim Fit Ribbed Crop Top",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["SLIM FIT"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Top",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-gardenia-printed-oversized-sweatshirt-504062-1671457112-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Pink OVERSIZED FIT Ribbed Crop Top",
    rating: 4.6,
    price: 638,
    mrp: 1599,
    off:"63%",
    fit_design:["OVERSIZED FIT"] ,
    color:["Pink"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Top",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //jeans denim for girls---
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-washed-wide-leg-fit-jeans-585087-1679660184-1.jpg",
    merchandise:"ANGEL FAB",
    name: "Women's Blue Washed Wide Leg Fit Jeans",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["WIDE LEG FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-loose-comfort-fit-jeans-585085-1679660534-1.jpg",
    merchandise:"ANGEL FAB",
    name: "Women's Blake Washed Wide Leg Fit Jeans",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["WIDE LEG FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-loose-comfort-fit-jeans-585080-1679660688-1.jpg",
    merchandise:"ANGEL FAB",
    name: "Women's Blue Washed Wide Leg Fit Jeans",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["WIDE LEG FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-blue-washed-distressed-boyfriend-fit-jeans-584965-1679563566-1.jpg",
    merchandise:"ANGEL FAB",
    name: "Women's Blue Washed Distressed Boyfriend Fit Jeans",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["WIDE LEG FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-black-bootcut-jeans-584971-1679563385-1.jpg",
    merchandise:"ANGEL FAB",
    name: "Women's Black Bootcut Jeans",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["WIDE LEG FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "Jeans",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //plus size complete arrya---
  {
    img:"https://images.bewakoof.com/t640/black-full-sleeve-plus-size-t-shirt-326615-1655750065-1.jpg",
    merchandise:"Bewakoof®",
    name: "Black Full Sleeve Plus Size Slim Fit T-Shirt",
    rating: 4.6,
    price: 1038,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-Shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/navy-blue-plus-size-casual-shorts-324728-1655748266-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["Navy"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/navy-blue-plus-size-casual-shorts-324728-1655748266-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["Navy"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-mickey-trio-call-dl-regular-fit-t-shirt-567871-1675689187-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["Navy"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/iron-man-of-war-full-sleeves-plus-size-printed-t-shirt-avl-340243-1656195612-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["yellow"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: true,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/women-s-yellow-i-like-to-moove-it-graphic-printed-plus-size-boyfriend-t-shirt-584934-1679641293-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["yellow"],
    size: ['s','m','2xl','3xl',],
    gender: "female",
    category: "T-Shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-sunset-block-graphic-printed-plus-size-t-shirt-589267-1681391917-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/iron-man-of-war-full-sleeves-plus-size-printed-t-shirt-avl-340243-1656195612-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-black-gyaan-graphic-printed-plus-size-t-shirt-589269-1681392231-1.jpg",
    merchandise:"Bewakoof®",
    name: "Navy Blue Plus Size Casual Shorts",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "T-Shirt",
    bestseller: false,
    newarrive: true,
    buy3at999: true,
  },
  //JACKET
  {
    img:"https://images.bewakoof.com/t1080/men-s-plus-size-navy-sage-solid-puffer-reversible-jacket-498968-1669640573-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Sage & Navy Plus Size Reversible Puffer Jacket",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["navy"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Jacket",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  //kurta for men
  {
    img:"https://images.bewakoof.com/t1080/men-s-solid-olive-relaxed-fit-long-kurta-317775-1663931378-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Olive Relaxed Fit Long Kurta",
    rating: 4.6,
    price: 798,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:["olive"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "Kurta",
    bestseller: false,
    newarrive: true,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-mustard-relaxed-fit-long-kurta-317794-1663931548-5.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Sage & Navy Plus Size Reversible Puffer kurta",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["PLUS SIZE"] ,
    color:["mustard"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "kurta",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //shirt for men
  {
    img:"https://images.bewakoof.com/t1080/men-s-linen-color-block-half-sleeves-shirt-362763-1656176753-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Color Block Shirt",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/men-s-black-printed-slim-fit-shirt-589571-1681732311-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Color Block Shirt",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:["black"],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-linen-color-block-half-sleeves-shirt-362763-1656176753-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Color Block Shirt",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
  {
    img:"https://images.bewakoof.com/t1080/men-s-linen-color-block-half-sleeves-shirt-362763-1656176753-1.jpg",
    merchandise:"Bewakoof®",
    name: "Men's Blue Color Block Shirt",
    rating: 4.6,
    price: 498,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:[null],
    size: ['s','m','2xl','3xl',],
    gender: "male",
    category: "shirt",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  //pants for women
  {
    img:"https://images.bewakoof.com/t640/women-s-purple-ribbed-wide-leg-pants-551820-1680689127-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Purple Ribbed Wide Leg Pants",
    rating: 4.6,
    price: 898,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:["purple"],
    size: ['s','m','2xl','3xl'],
    gender: "female",
    category: "pants",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/women-s-brown-ribbed-side-slit-pants-556817-1680689575-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Purple Ribbed Wide Leg Pants",
    rating: 4.6,
    price: 898,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:["brown"],
    size: ['s','m','2xl','3xl'],
    gender: "female",
    category: "pants",
    bestseller: false,
    newarrive: false,
    buy3at999: false,
  },
  {
    img:"https://images.bewakoof.com/t640/women-s-blue-ribbed-wide-leg-pants-551821-1680689460-1.jpg",
    merchandise:"Bewakoof®",
    name: "Women's Purple Ribbed Wide Leg Pants",
    rating: 4.6,
    price: 898,
    mrp: 1599,
    off:"63%",
    fit_design:["RELAXED FIT"] ,
    color:["blue"],
    size: ['s','m','2xl','3xl'],
    gender: "female",
    category: "pants",
    bestseller: false,
    newarrive: false,
    buy3at999: true,
  },
];

total_item[77].img="https://images.bewakoof.com/t1080/women-s-black-slim-fit-t-shirt-232388-1665664326-1.jpg";

